# Generated by Django 5.1.7 on 2025-03-20 21:22

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('coderr_app', '0003_review'),
    ]

    operations = [
        migrations.RenameField(
            model_name='offerdetail',
            old_name='owner',
            new_name='user',
        ),
    ]
