# Generated by Django 5.1.7 on 2025-03-27 16:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('coderr_app', '0004_rename_owner_offerdetail_user'),
    ]

    operations = [
        migrations.CreateModel(
            name='BaseInfo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('review_count', models.IntegerField()),
                ('average_rating', models.IntegerField()),
                ('business_profile_count', models.IntegerField()),
                ('offer_count', models.IntegerField()),
            ],
        ),
    ]
